### ISSUE TITLE
测试版本 url 错误

### ISSUE THREAD

**Issue by hasbai** [OpenTreeHole/vue#13]
opentreehole.github.io 的测试版本下 api 应该访问 hole.hath.top ，而目前访问的是 www.fduhole.com ，造成测试版本无法使用

**Comment by hasbai** [comment]
是否需要将测试服的域名设置为 test.fduhole.com ，这样前端直接访问 /api 就可以了

**Comment by dest1n1s** [comment]
> 是否需要将测试服的域名设置为 test.fduhole.com ，这样前端直接访问 /api 就可以了

目前这样子似乎没有问题，先不用改了吧
