### ISSUE TITLE
置顶帖需要特殊样式标记

### ISSUE THREAD

**Issue by KYLN24** [OpenTreeHole/vue#7]
![image](https://user-images.githubusercontent.com/54014142/145855153-96768704-9430-4447-b8f7-15fbfbb5c76d.png)

**Comment by dest1n1s** [comment]
现在置顶帖应该右上角是有'pin'图标作为标记的？不知道你的情况如何复现
![image](https://user-images.githubusercontent.com/13075143/149049626-f0872322-ac6a-4223-9fda-a3928f7add3f.png)

**Comment by KYLN24** [comment]
今天再打开似乎没有问题了，或许是个随机bug
